"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
type Props={courseId:string;courseName:string};
type Profile={username:string|null;display_name:string|null};
type Checkin={id:string;score:number|null;notes:string|null;created_at:string;profiles?:Profile|null};
type Round={id:string;total_score:number;holes_played:number|null;notes:string|null;created_at:string;profiles?:Profile|null};
function player(p?:Profile|null){return p?.display_name||p?.username||"DiscPlus player"}
export function CourseCommunityPanel({courseId,courseName}:Props){const supabase=useMemo(()=>createClient(),[]); const [userId,setUserId]=useState<string|null>(null); const [checkins,setCheckins]=useState<Checkin[]>([]); const [rounds,setRounds]=useState<Round[]>([]); const [notes,setNotes]=useState(""); const [score,setScore]=useState(""); const [roundScore,setRoundScore]=useState(""); const [holes,setHoles]=useState("18"); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
async function load(){setLoading(true); if(!supabase){setLoading(false);return} const {data:{user}}=await supabase.auth.getUser(); setUserId(user?.id||null); const [c,r]=await Promise.all([supabase.from("checkins").select("id,score,notes,created_at,profiles(username,display_name)").eq("course_id",courseId).order("created_at",{ascending:false}).limit(15),supabase.from("rounds").select("id,total_score,holes_played,notes,created_at,profiles(username,display_name)").eq("course_id",courseId).order("total_score",{ascending:true}).limit(15)]); setCheckins((c.data||[]) as any); setRounds((r.data||[]) as any); setLoading(false)}
useEffect(()=>{load()},[courseId]);
async function saveCheckin(e:FormEvent){e.preventDefault(); setMessage(""); if(!supabase||!userId){setMessage("Log in or create an account to save a check-in.");return} const payload={user_id:userId,course_id:courseId,course_name:courseName,score:score?Number(score):null,notes:notes.trim()||null}; const {error}=await supabase.from("checkins").insert(payload); if(error){setMessage(error.message);return} setNotes("");setScore("");setMessage("Check-in saved."); await load()}
async function saveRound(e:FormEvent){e.preventDefault(); setMessage(""); if(!supabase||!userId){setMessage("Log in or create an account to post a score.");return} const total=Number(roundScore); if(!Number.isFinite(total)){setMessage("Enter a valid score.");return} const {error}=await supabase.from("rounds").insert({user_id:userId,course_id:courseId,course_name:courseName,total_score:total,holes_played:Number(holes)||18}); if(error){setMessage(error.message);return} setRoundScore("");setMessage("Score posted."); await load()}
return <section className="panel page-stack"><div><span className="eyebrow">Community</span><h2>Check-ins and scores</h2><p className="dashboard-copy">Public visitors can view course activity. Logged-in players can add check-ins and scores.</p></div>{!supabase?<p className="notice">Supabase is not configured. Add your environment variables to enable accounts and posting.</p>:!userId?<p className="notice"><Link href="/login">Log in</Link> or <Link href="/signup">create an account</Link> to post.</p>:null}{message?<p className="notice">{message}</p>:null}<div className="grid"><form className="panel page-stack" onSubmit={saveCheckin}><h3>Check in</h3><label>Notes<textarea className="form-input" disabled={!userId} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="How is the course today?"/></label><label>Optional score<input className="form-input" disabled={!userId} type="number" value={score} onChange={e=>setScore(e.target.value)} placeholder="43"/></label><button className="button" disabled={!userId}>Save check-in</button></form><form className="panel page-stack" onSubmit={saveRound}><h3>Post score</h3><label>Total score<input className="form-input" disabled={!userId} required type="number" value={roundScore} onChange={e=>setRoundScore(e.target.value)} placeholder="43"/></label><label>Holes played<input className="form-input" disabled={!userId} type="number" value={holes} onChange={e=>setHoles(e.target.value)} placeholder="18"/></label><button className="button" disabled={!userId}>Add score</button></form></div><section className="panel"><h3>Leaderboard</h3>{loading?<p className="dashboard-copy">Loading...</p>:rounds.length===0?<p className="dashboard-copy">No scores posted yet.</p>:<div className="dashboard-feed">{rounds.map((r,i)=><article className="post-card" key={r.id}><div className="post-card-top"><div><p className="post-author">#{i+1} {player(r.profiles)}</p><p className="post-meta">{r.holes_played||18} holes • {new Date(r.created_at).toLocaleDateString()}</p></div><span className="badge">{r.total_score}</span></div></article>)}</div>}</section><section className="panel"><h3>Recent check-ins</h3>{!loading&&checkins.length===0?<p className="dashboard-copy">No check-ins yet.</p>:<div className="dashboard-feed">{checkins.map(c=><article className="post-card" key={c.id}><div className="post-card-top"><div><p className="post-author">{player(c.profiles)}</p><p className="post-meta">{new Date(c.created_at).toLocaleString()}</p></div>{c.score!==null?<span className="badge">{c.score}</span>:null}</div>{c.notes?<p className="post-content">{c.notes}</p>:null}</article>)}</div>}</section></section>}
